version: '3'
services:
  gym-time-pg: 
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSGRES_DATABASE=gym-time